### ISSUE TITLE
use attribute for filter an userlist

### ISSUE THREAD

**Issue by tkart38** [Remo/attribute-free-form#3]
hi
how can i use the attribute for filter an userlist?

**Comment by Remo** [comment]
can you please be a bit more specific? What's your problem? Is there an error message when you filter a userlist using this attribute?

**Comment by tkart38** [comment]
yes sorry.
there are not error.

but I don't understand how to use the filter with the handle 
I need to filter by the Name 
for example i've to use like this :
$list->filterByAttribute("test_attribute",' ?? ' '==');
i don't know if iv'e to use the array field  like ['Name' => 'Remo'] 


O i need to use getQueryObject for make the filter query?

thanks for the help.

**Comment by Remo** [comment]
that's pretty hard to do because it's all stored in one field. If everyone was using MySQL 5.7 I could store things in a JSON field, but till then that's not possible unless you implement a full scan, but that I won't add because I'm sure I'd get a lot of complaints about it being slow and so on.. Sorry

**Comment by tkart38** [comment]
ok thanks
this problem is not present with the multi_text right? because all are stored with the handle for all the child of the attribute. 

than i've to do the search form for multi_text. Is hard to do?if you can give me some advice I'll try to do without disturb you again. I hope :-p

thanks again for your help
bye

**Comment by Remo** [comment]
I'm afraid, but it's the same problem there too since I'm saving it as a JSON string as well. It would be possible to refactor that attribute though, but since I never received much feedback about this I would only do that if there's a (paying) customer in need of that.
Honestly, it sounds like you're better of creating your own custom attribute!
